name: Build and Deploy
on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: 'develop'

jobs:
  CheckoutCode:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'develop' }}
          fetch-depth: 0
          
  FetchSecretsFromVault:
    runs-on: [ubuntu-latest] 
    outputs: 
      BLACKDUCK_TOKEN: ${{ steps.vault.outputs.BLACKDUCK_TOKEN }} 
      SONAR_TOKEN: ${{ steps.vault.outputs.SONAR_TOKEN }}
    steps:
      - name: Get Secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: http://54.159.52.131:8200/
          method: userpass
          path: userpass
          username: "admin1"
          password: "admin123"
          exportEnv: true
          secrets: | 
            app1/data/blackduck blackduck_apiToken | BLACKDUCK_TOKEN;
            app1/data/sonar SONAR_TOKEN 
 
      - name: echo
        run: | 
          echo "${{ env.SONAR_TOKEN }}"
          echo "${{ env.BLACKDUCK_TOKEN }}"
          echo "BLACKDUCK_TOKEN1=${{ env.BLACKDUCK_TOKEN }}" >> $GITHUB_ENV
          echo "SONAR_TOKEN1=${{ env.SONAR_TOKEN }}" >> $GITHUB_ENV
#          echo "BLACKDUCK_TOKEN: ${{ needs.FetchSecretsFromVault.outputs.BLACKDUCK_TOKEN }}"
#          echo "SONAR_TOKEN: ${{ needs.FetchSecretsFromVault.outputs.SONAR_TOKEN }}" 

  Test_secrets: 
    runs-on: ubuntu-latest
    needs: FetchSecretsFromVault
    steps: 
      - name: Test_secrets
        run: | 
          echo ${{ env.BLACKDUCK_TOKEN1 }}
          echo ${{ env.SONAR_TOKEN1 }} 
#          echo "BLACKDUCK_TOKEN: ${{ needs.FetchSecretsFromVault.outputs.BLACKDUCK_TOKEN }}"
#          echo "SONAR_TOKEN: ${{ needs.FetchSecretsFromVault.outputs.SONAR_TOKEN }}"

#  SonarQubeAnalysis:
#    runs-on: [ubuntu-latest]
#    needs: FetchSecretsFromVault  
#    steps:
#      - name: SonarQube analysis
#        uses: SonarSource/sonarqube-scan-action@v4.2.0
#        env:
#          SONAR_HOST_URL: http://54.159.52.131:9000/
#          SONAR_TOKEN: ${{ needs.FetchSecretsFromVault.outputs.SONAR_TOKEN  }}
#
          
          
          
          


